config/routes.rb
App::Application.routes.draw do
  root :to => "home#index"
  get '/blog', to: redirect('http://www.makeworldwide.blogspot.co.uk', status: 302)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions', invitations: 'users/invitations',
    registrations: 'users/registrations' }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount StripeEvent::Engine => '/stripe/webhooks'

  resources :users
  devise_scope :user do
    post 'invitation/mass' => "users/invitations#mass", as: :mass_invitation
    post 'invitation/generate-link' => "users/invitations#generate_link", as: :generate_invitation_link
    post 'invitation/grant-access' => "waiting_lists#grant_access", as: :grant_access_to_waiting_list
  end
  resources :waiting_lists

  resources :causes
  scope 'charities/dashboard' do
    get 'current-status' => "charities#current_status", as: 'charities_dashboard'
    get 'approvals-new-staff' => "charities#approvals_new_staff", as: 'approvals_new_staff'
  end
  resources :charities, except: :index do
    resources :projects, only: [:new, :create, :edit, :update]
    get "colleagues" => "charities#colleagues", as: :colleagues
    get "projects/:id/trends" => "projects#trends", as: :project_trends
  end

  resources :charity_registrations, only: [:new, :create]
  resources :charity_join_requests, only: [:new, :create]
  resources :stories
  resources :welcome_messages, only: [:show, :destroy]
  resources :projects, only: [:show, :destroy] do
    resources :stories
  end

  # GoCardless
  scope "gocardless" do
    scope "pre-auth" do
      get "index" => "gocardless#pre_auth_index"
      post "submit" => "gocardless#pre_auth_submit"
      get "confirm" => "gocardless#pre_auth_confirm"
    end
    scope "subscription" do
      get "index" => "gocardless#subscription_index"
      post "submit" => "gocardless#subscription_submit"
      get "confirm" => "gocardless#subscription_confirm"
    end
    get "merchant_account_authorization/:state" => "gocardless#merchant_account_authorization", as: :gocardless_merchant_account_authorization
    get "merchant_account_authorization_confirmed" => "gocardless#merchant_account_authorization_confirmed", as: :gocardless_merchant_account_authorization_confirmed
  end
  scope "stripe" do
    # Tests
    get "charges/new" => "stripe#charges_new", as: :new_stripe_charge
    post "charges/create" => "stripe#charges_create", as: :create_stripe_charge
    get "charges/customer" => "stripe#charges_customer", as: :customer_stripe_charge
    get "subscription" => "stripe#subscription", as: :create_stripe_subscription
    # Production
    post "create_charges(/:gift_aid_charity_ids)" => "stripe#create_charges", as: :create_stripe_charges
    post "create_subscriptions(/:gift_aid_charity_ids)" => "stripe#create_subscriptions", as: :create_stripe_subscriptions
    get "merchant_account_authorization/:state" => "stripe#merchant_account_authorization", as: :stripe_merchant_account_authorization
    get "merchant_account_authorization_confirmed" => "stripe#merchant_account_authorization_confirmed", as: :stripe_merchant_account_authorization_confirmed
    get "cancel_subscriptions/:project_id" => "stripe#cancel_subscription", as: :cancel_stripe_subscription
  end

  # _______________ Static pages
  get 'terms-and-conditions' => "pages#terms_and_conditions", as: :terms_and_conditions
  get 'privacy-and-cookies' => "pages#privacy_and_cookies", as: :privacy_and_cookies

  get 'get-started' => "users#waiting_list", as: :waiting_list
  get 'guest/sign-up' => "users#skip_invitation_and_sign_up", as: :skip_invitation_and_sign_up
  post 'guest/create-skipped-invitation' => "users#create_skipped_invitation", as: :create_skipped_invitation

  get "charity-sign-up" => "pages#charity_sign_up", as: :charity_sign_up
  get "personal-sign-up" => "pages#personal_sign_up", as: :personal_sign_up

  get 'change-store-projects' => "pages#change_store_projects", as: 'change_store_projects'
  get 'change-store-projects-category' => "pages#change_store_projects_category"

  get 'project-stage-fundraising' => "pages#project_stage_fundraising"
  get 'project-stage-development-impact-completion' => "pages#project_stage_development_impact_completion"

  get 'checkout/(:project_id)' => "pages#checkout", as: 'checkout'
  get 'payment' => "pages#payment", as: 'payment'

  get 'me' => "pages#me"

  get 'charity-or-bundle-home' => "pages#charity_or_bundle_home", as: 'charity_or_bundle_home'
  get 'charity-or-bundle-updates' => "pages#charity_or_bundle_updates"

  get 'dashboard' => "pages#dashboard"

  get 'received-invitation' => "pages#received_invitation"

  get 'my-home' => "pages#my_home", as: 'my_home'

  get 'causes-preferences-causes' => "pages#causes_preferences_causes", as: 'causes_preferences_causes'
  get 'causes-preferences-places' => "pages#causes_preferences_places"
  get 'causes-preferences-interests' => "pages#causes_preferences_interests", as: 'causes_preferences_interests'
  get 'causes-preferences-collect' => "pages#collect", as: 'causes_preferences_collect'

  get 'defaultsite' => "pages#defaultsite" # 1and1 redirection (301)

  # API
  namespace :api, format: :json do
    namespace :v1 do
      resources :users do
        collection do
          get :search
          get :me
          get :facebookconnect
          # follow
          get :is_following
          post :follow
          post :unfollow
          # cart
          get :cart_projects
          get :cart_add
          get :cart_remove
          get :cart_clear
          get :cart_total
          # likes
          get :like_an_update
          get :unlike_an_update
          # other
          get :update_causes
          get :get_places
          get :update_places
          get :update_intelligent_matching
        end
      end
      resources :causes do
        collection do
          get :search
        end
      end
      resources :lifestyle_checkouts
      resources :charities do
        collection do
          get :search
        end
      end
      resources :charity_join_requests do
        collection do
          post :approve
          post :reject
          get :pending
        end
      end
      resources :projects do
        collection do
          get :search
          get :suggested
          get :selected
        end
      end
      resources :faqs
      resources :comments
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApplicationController
  skip_authorize_resource only: [:search, :facebookconnect, :me,
                                 :follow, :unfollow, :is_following,
                                 :cart_projects, :cart_add, :cart_remove,
                                 :cart_clear, :cart_total,
                                 :update_causes, :get_places,
                                 :update_places, :update_payment_form,
                                 :like_an_update, :unlike_an_update]

  def search
    text = params[:query] || ""

    offset = params[:offset] || 0
    limit = params[:limit] || 10

    a = []
    text.split().each do |word|
      User.where("LOWER(last_name) LIKE ?", "%#{word.downcase}%").each do |user|
        (a.include?(user)) ? a.insert(0, a.delete(user)) : a << user
      end
      User.where("LOWER(first_name) LIKE ?", "%#{word.downcase}%").each do |user|
        (a.include?(user)) ? a.insert(0, a.delete(user)) : a << user
      end
      User.where("LOWER(name) LIKE ?", "%#{word.downcase}%").each do |user|
        (a.include?(user)) ? a.insert(0, a.delete(user)) : a << user
      end
    end
    @users = a[offset, limit]

    render :index
  end

  def facebookconnect
    if @user = User.find_for_facebook_token(params[:facebookToken])
      sign_in @user
      render :me
    else
      render text: {user: "wrong facebook token"}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  def show
    @user = User.find(params[:id])
    authorize! :show, @user
  end

  def me
    @user = current_user
    render :me
  end

  # Follow
  def follow
    target = get_following
    current_user.follow(target) if target
    render json: true
  end

  def unfollow
    target = get_following
    current_user.stop_following(target) if target
    render json: true
  end

  def is_following
    target = get_following
    is_following = if target
                     current_user.following?(target)
                   else
                     false
                   end
    render json: is_following
  end

  def get_following
    if params[:charity_id].present?
      Charity.find(params[:charity_id])
    elsif params[:user_id].present?
      User.find(params[:user_id])
    end
  end

  # Cart
  def cart_projects
    get_cart_projects
    render :cart_projects
  end

  def cart_add
    project = Project.find(params[:project_id])
    @cart.add(project, params[:price])
    get_cart_projects
    if Rails.env.production?
      @tracker.track(0, 'Add to basket', {
          'Logged in type' => 'Yes',
          'Existing registration' => 'Yes',
          'Country' => '',
          'Date of action' => Time.now,
          'Number of website visits' => '',
          'Number of Makerble logins' => current_user.sign_in_count,
          'Source' => '',
          'Campaign code' => '',

          'Choice type' => 'Cause',
          'Number of projects added' => '1',
          'Name of projects' => project.name,
          'Logged in type' => 'Yes',
          'Existing registration' => 'Yes'
      })
    end
    render :cart_projects
  end

  def cart_remove
    project = Project.find(params[:project_id])
    @cart.remove(project, params[:quantity])
    get_cart_projects
    render :cart_projects
  end

  def cart_clear
    @cart.clear
    get_cart_projects
    render :cart_projects
  end

  def cart_total
    render json: @cart.total
  end

  def get_cart_projects
    @projects = []
    @cart.shopping_cart_items.each { |item| @projects << Project.find(item.item_id) }
    @projects
  end
  # .Cart

  def update_causes
    conditions = {}
    @causes = if params[:ids].present?
                conditions[:id] = params[:ids].split(',')
                Cause.where(conditions)
              else
                []
              end

    current_user.causes.clear
    @causes.each { |cause| current_user.causes << cause }
    current_user.save

    render json: current_user.causes.to_json(only: [:id, :name])
  end

  def get_places
    render json: current_user.place_list
  end

  def update_places
    current_user.place_list = params[:places]
    current_user.save(validate: false)
    render json: current_user.place_list
  end

  def update_intelligent_matching
    current_user.intelligent_matching = (params[:value] == "true")
    tracker_text = current_user.intelligent_matching ? 'Yes' : 'No'
    if Rails.env.production?
      @tracker.track(0, 'Cause info', {
          'Logged in type' => 'Yes',
          'Existing registration' => 'Yes',
          'Country' => '',
          'Date of action' => Time.now,
          'Number of website visits' => '',
          'Number of Makerble logins' => current_user.sign_in_count,
          'Source' => '',
          'Campaign code' => '',

          'Facebook matching' => tracker_text
      })
    end
    current_user.save(validate: false)
    render json: current_user.intelligent_matching
  end

  def like_an_update
    target = if params[:likable_type] == "Story"
               Story.find(params[:likable_id])
             elsif params[:likable_type] == "Achievement"
               Achievement.find(params[:likable_id])
             end
    current_user.likes(target) if target

    if target
      render json: target.to_json(only: :id)
    else
      render json: false
    end
  end

  def unlike_an_update
    target = if params[:likable_type] == "Story"
               Story.find(params[:likable_id])
             elsif params[:likable_type] == "Achievement"
               Achievement.find(params[:likable_id])
             end

    if target
      target.unliked_by(current_user)
      render json: target.to_json(only: :id)
    else
      render json: false
    end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  def edit
    session[:invitation_token] = params[:invitation_token] if params[:invitation_token].present?
    redirect_to new_user_registration_url
  end

  def generate_link
    if !params[:user].present? || !params[:user][:email].present? || (params[:user][:email] =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i).nil?
      redirect_to :back, notice: 'Please make sure that your email address is valid.'
    else
      user = User.invite!(email: params[:user][:email]) do |u|
        u.skip_invitation = true
      end
      redirect_to :back, notice: "Link for #{user.email}: #{accept_invitation_url(user, :invitation_token => user.raw_invitation_token)}"
    end
  end

  def mass
    emails = params[:invitation][:emails_list].split(',').map(&:chomp)
    User.send_mass_invitations(emails)
    redirect_to root_path, notice: 'The invitations are being sent.'
  end

  def create
    if !current_user.has_role?(:admin) && current_user.invitations.count > 2 # TODO check that the invitation count is ok
      WaitingList.create(email: params[:user][:email])
      DeviseMailer.delay.invitation_to_join_the_waiting_list(params[:user][:email], current_user)
      redirect_to :back, notice: 'This email has been added to the waiting list. You have already used your two direct invitations.'
    elsif params[:invitation].present? && params[:invitation][:waiting_list].present? && params[:invitation][:waiting_list] == "1"
      WaitingList.create(email: params[:user][:email])
      DeviseMailer.delay.invitation_to_join_the_waiting_list(params[:user][:email], current_user)
      redirect_to root_path, notice: 'This email has been added to the waiting list.'
    else
      if Rails.env.production?
        @tracker.track(0, 'Advocacy', {
            'Logged in type' => 'Yes',
            'Existing registration' => 'Yes',
            'Country' => '',
            'Date of action' => Time.now,
            'Number of website visits' => '',
            'Number of Makerble logins' => current_user.sign_in_count,
            'Source' => '',
            'Campaign code' => '',

            'Personal invite' => 'Yes',
            'Personal invite number' => 'undefined',
            'Activated Facebook sharing' => current_user.intelligent_matching ? 'Yes' : 'No',
            'Activated Facebook profile' => current_user.facebook_token ? 'Yes' : 'No',
            'Buy a friend a gift voucher' => 'No'
        })
      end
      super
    end
  end

  protected
    def has_invitations_left?
      true # 2 direct invitations and then
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    auth_hash_service = AuthHashService.new(auth_hash, current_user, session[:invitation_token])
    @user = auth_hash_service.find_or_create_from_auth_hash
    session[:invitation_token] = nil
    handle_user "Facebook"
  end

  def twitter
    auth_hash_service = AuthHashService.new(auth_hash, current_user)
    @user = auth_hash_service.find_or_create_from_auth_hash
    handle_user "Twitter"
  end

  private
    def handle_user kind
      if @user.persisted?
        handle_persisted_user(kind)
      else
        handle_not_persisted_user(kind)
      end
    end

    def handle_persisted_user(kind)
      # OmniAuth requests save the original URL in 'omniauth.origin'
      # Changes the default after_sign_in_path_for when the request originates from "/personal-sign-up"
      if request.env['omniauth.origin'] == personal_sign_up_url
        session[:return_to_url] = request.env['omniauth.origin']
      end

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => kind) if is_navigational_format?
    end

    def handle_not_persisted_user(kind)
      if kind == "Facebook"
        session["devise.facebook_data"] = request.env["omniauth.auth"]
      elsif kind == "Twitter"
        session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      end
      redirect_to new_user_registration_url
    end

    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    @redirect_to_path = params[:redirect_to_path] if params[:redirect_to_path]
    super
  end

  protected
  attr_reader :redirect_to_path

  def after_sign_up_path_for(resource)
    @redirect_to_path.presence || super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    if session[:skip_invitation].present? && session[:skip_invitation] == true
      redirect_to skip_invitation_and_sign_up_path
    end
  end
end

app/views/users/_change_column.html.haml
.bloc
  .connect
    - if user_signed_in? && current_user != @user
      = link_to nil, class: "follow-user", data: { active: "#{@is_following ? "true" : "false"}", user_id: @user.id } do
        .follow
          .sprites-follow
          .name= @is_following ? "Unfollow" : "Follow"
    - if false && (!user_signed_in? || current_user != @user)
      = link_to "#" do
        .sprites-message
        .name
          Message

  .picture-and-score
    .profile-picture
      = image_tag @user.avatar(:square), class: "img-flag", width: '117px'

    .score
      %h5= "#{@user.name}'s Makerble change"
      - @user.change_score.to_s.chars.map(&:to_i).each do |digit|
        %div{class: "number sprites-digit-#{digit}"}

  %hr

  - if false
    .medals
      .pull-right.actions
        = link_to "See all" ,"#"
      %h5 Medals (25)
      .list
        - 3.times do
          .medal
            = link_to nil do
              .sprites-medal
        - 1.times do
          .medal
            = link_to nil do
              .sprites-medal-inactive

  %ul.inline.statistics
    %li
      .number= @user.inspired.count
      .name Inspired
    %li
      .number= @user.helped_projects.count
      .name= @user.helped_projects.count < 2 ? "Project" : "Project".pluralize
    %li
      .number= @user.followers.count
      .name= @user.followers.count < 2 ? "Follower" : "Follower".pluralize
    %li
      .number= @user.follows_by_type('User').count
      .name= @user.follows_by_type('User').count < 2 ? "Following" : "Following".pluralize

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      .alert.alert-error
        The form contains #{pluralize(@user.errors.count, "error")}.
      %ul.alert.alert-error
        - @user.errors.full_messages.each do |msg|
          %li
            * #{msg}

  .form-inputs
    = f.input :name, autofocus: true
    = f.input :avatar
    .change-password
      = f.input :current_password
      = f.input :password
      = f.input :password_confirmation
    - if @user.uid && !@user.uid.empty?
      %p
        %em Your facebook is connected
    - else
      .field
        = link_to "Connect my facebook account", omniauth_authorize_path('user', :facebook)
    .field
      = link_to "Change my password", "", class: 'change-password-link'

  .form-actions
    = f.button :submit, "Save changes"
    = link_to 'Cancel', @user, class: 'btn'

app/views/users/_show.html.haml
= render 'timeline/show'

.container
  .row
    .span12
      .row
        .span8.project-progress
          - if user_signed_in? && @user == current_user && @welcome_messages.any?
            %h2
              Welcome messages

            .bloc.welcome-messages
              - @welcome_messages.each do |message|
                .row
                  %h4
                    = link_to message.project do
                      Project: #{message.project.name}
                  %h5= message.headline
                  %p= message.text
                %hr

          %h2
            Project progress
            - if false
              %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
                .sprites-infos

          - if @user.helped_projects.any?
            .bloc
              - @user.helped_projects[0, 4].reverse.each do |project| # TODO Display more projects
                .row
                  .project-progress-overview
                    - if false
                      .pull-right
                        %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
                          .sprites-add-people
                        %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
                          .sprites-add-money
                    %h4= link_to truncate(project.name, length: 80), project
                  .span.helping
                    %h5 Helping
                    = link_to image_tag(project.help_image(:square), width: '134px'), project
                  .span.making
                    %h5
                      Making
                      - if project.current_project_make
                        (#{humanized_money_with_symbol(project.current_project_make.donations_total)}
                        of #{humanized_money_with_symbol(project.current_project_make.cost)})
                      - elsif project.previous_project_make
                        (#{humanized_money_with_symbol(project.previous_project_make.donations_total)}
                        of #{humanized_money_with_symbol(project.previous_project_make.cost)})
                    .details
                      - if project.current_project_make
                        = image_tag project.current_project_make.make.icon(:square)
                        - progress = project.current_project_make.progress
                      - elsif project.previous_project_make
                        = image_tag project.previous_project_make.make.icon(:square)
                        - progress = project.previous_project_make.progress
                      - else
                        = image_tag "sprites/icons/seeds.png"
                        - progress = 0
                      .project-progress-stripes
                        - progress = 15 if progress < 15
                        - (progress / 10).times do |index|
                          %div{:class => "sprites-progress-stripe-#{index}"}
                        - (10 - progress / 10).times do |index|
                          %div{:class => "sprites-progress-stripe-empty"}

                  .span.change
                    %h5 Change
                    .medal
                      - if project.current_project_change
                        = image_tag project.current_project_change.change.icon(:small), width: '79px'
                        .count= project.current_project_change.changes_total
                      - elsif project.previous_project_change
                        = image_tag project.previous_project_change.change.icon(:small), width: '79px'
                        .count= project.previous_project_change.changes_total
                    - if false
                      .action
                        = link_to "View Total", "#"

                %hr

              /= render 'pagination'

          - else
            Nothing to show here.

        .span4.achievements
          - if @user == current_user
            .pull-right.actions
              = link_to "Account settings" , edit_user_path(@user)
          %h2
            Achievements
            - if false
              %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
                .sprites-infos

          = render 'users/change_column'

  #followings
    %h2
      Tiles
      - if false
        %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
          .sprites-infos
    = render "projects/change_update", columns: 3

app/views/users/edit.html.haml
.container
  %h1 Account settings

  = render 'form'

app/views/users/show.html.haml
= render 'show'

app/views/users/skip_invitation_and_sign_up.html.haml
.container
  .row
    .span6
      %h1 Sign up (step 1/2)

      = simple_form_for User.new, :url => create_skipped_invitation_path, :html => {:method => :post} do |f|
        .form-field
          = label :user, :email
          = email_field :user, :email
        .submit
          = f.submit "Sign up"

    .span6
      %h1 Already got an account?
      = link_to omniauth_authorize_path('user', :facebook) do
        .fb-login-button
          .sprites-facebook
          Login using Facebook
      %hr
      %h4 Or with your email address
      = simple_form_for(User.new, as: 'user', url: session_path('user')) do |f|
        .form-inputs
          = f.input :email, required: false, autofocus: true
          = f.input :password, required: false
          = f.input :remember_me, as: :boolean
        .form-actions
          = f.button :submit, "Sign in"
      = link_to "Forgot your password?", new_password_path('user')

app/views/users/waiting_list.html.haml
.container
  .row
    .span6
      %h1 Join the waiting list

      = simple_form_for WaitingList.new, html: {method: :post} do |f|
        .form-field
          = f.label :email
          = f.email_field :email
        .submit
          = f.button :submit, "Sign up to waiting list"

    .span6
      %h1 Already got an account?
      = link_to omniauth_authorize_path('user', :facebook) do
        .fb-login-button
          .sprites-facebook
          Login using Facebook
      %hr
      %h3 Or with your email address
      = simple_form_for(User.new, as: 'user', url: session_path('user')) do |f|
        .form-inputs
          = f.input :email, required: false, autofocus: true
          = f.input :password, required: false
          = f.input :remember_me, as: :boolean
        .form-actions
          = f.button :submit, "Sign in"
      = link_to "Forgot your password?", new_password_path('user')