config/routes.rb
App::Application.routes.draw do
  root :to => "home#index"
  get '/blog', to: redirect('http://www.makeworldwide.blogspot.co.uk', status: 302)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions', invitations: 'users/invitations',
    registrations: 'users/registrations' }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount StripeEvent::Engine => '/stripe/webhooks'

  resources :users
  devise_scope :user do
    post 'invitation/mass' => "users/invitations#mass", as: :mass_invitation
    post 'invitation/generate-link' => "users/invitations#generate_link", as: :generate_invitation_link
    post 'invitation/grant-access' => "waiting_lists#grant_access", as: :grant_access_to_waiting_list
  end
  resources :waiting_lists

  resources :causes
  scope 'charities/dashboard' do
    get 'current-status' => "charities#current_status", as: 'charities_dashboard'
    get 'approvals-new-staff' => "charities#approvals_new_staff", as: 'approvals_new_staff'
  end
  resources :charities, except: :index do
    resources :projects, only: [:new, :create, :edit, :update]
    get "colleagues" => "charities#colleagues", as: :colleagues
    get "projects/:id/trends" => "projects#trends", as: :project_trends
  end

  resources :charity_registrations, only: [:new, :create]
  resources :charity_join_requests, only: [:new, :create]
  resources :stories
  resources :welcome_messages, only: [:show, :destroy]
  resources :projects, only: [:show, :destroy] do
    resources :stories
  end

  # GoCardless
  scope "gocardless" do
    scope "pre-auth" do
      get "index" => "gocardless#pre_auth_index"
      post "submit" => "gocardless#pre_auth_submit"
      get "confirm" => "gocardless#pre_auth_confirm"
    end
    scope "subscription" do
      get "index" => "gocardless#subscription_index"
      post "submit" => "gocardless#subscription_submit"
      get "confirm" => "gocardless#subscription_confirm"
    end
    get "merchant_account_authorization/:state" => "gocardless#merchant_account_authorization", as: :gocardless_merchant_account_authorization
    get "merchant_account_authorization_confirmed" => "gocardless#merchant_account_authorization_confirmed", as: :gocardless_merchant_account_authorization_confirmed
  end
  scope "stripe" do
    # Tests
    get "charges/new" => "stripe#charges_new", as: :new_stripe_charge
    post "charges/create" => "stripe#charges_create", as: :create_stripe_charge
    get "charges/customer" => "stripe#charges_customer", as: :customer_stripe_charge
    get "subscription" => "stripe#subscription", as: :create_stripe_subscription
    # Production
    post "create_charges(/:gift_aid_charity_ids)" => "stripe#create_charges", as: :create_stripe_charges
    post "create_subscriptions(/:gift_aid_charity_ids)" => "stripe#create_subscriptions", as: :create_stripe_subscriptions
    get "merchant_account_authorization/:state" => "stripe#merchant_account_authorization", as: :stripe_merchant_account_authorization
    get "merchant_account_authorization_confirmed" => "stripe#merchant_account_authorization_confirmed", as: :stripe_merchant_account_authorization_confirmed
    get "cancel_subscriptions/:project_id" => "stripe#cancel_subscription", as: :cancel_stripe_subscription
  end

  # _______________ Static pages
  get 'terms-and-conditions' => "pages#terms_and_conditions", as: :terms_and_conditions
  get 'privacy-and-cookies' => "pages#privacy_and_cookies", as: :privacy_and_cookies

  get 'get-started' => "users#waiting_list", as: :waiting_list
  get 'guest/sign-up' => "users#skip_invitation_and_sign_up", as: :skip_invitation_and_sign_up
  post 'guest/create-skipped-invitation' => "users#create_skipped_invitation", as: :create_skipped_invitation

  get "charity-sign-up" => "pages#charity_sign_up", as: :charity_sign_up
  get "personal-sign-up" => "pages#personal_sign_up", as: :personal_sign_up

  get 'change-store-projects' => "pages#change_store_projects", as: 'change_store_projects'
  get 'change-store-projects-category' => "pages#change_store_projects_category"

  get 'project-stage-fundraising' => "pages#project_stage_fundraising"
  get 'project-stage-development-impact-completion' => "pages#project_stage_development_impact_completion"

  get 'checkout/(:project_id)' => "pages#checkout", as: 'checkout'
  get 'payment' => "pages#payment", as: 'payment'

  get 'me' => "pages#me"

  get 'charity-or-bundle-home' => "pages#charity_or_bundle_home", as: 'charity_or_bundle_home'
  get 'charity-or-bundle-updates' => "pages#charity_or_bundle_updates"

  get 'dashboard' => "pages#dashboard"

  get 'received-invitation' => "pages#received_invitation"

  get 'my-home' => "pages#my_home", as: 'my_home'

  get 'causes-preferences-causes' => "pages#causes_preferences_causes", as: 'causes_preferences_causes'
  get 'causes-preferences-places' => "pages#causes_preferences_places"
  get 'causes-preferences-interests' => "pages#causes_preferences_interests", as: 'causes_preferences_interests'
  get 'causes-preferences-collect' => "pages#collect", as: 'causes_preferences_collect'

  get 'defaultsite' => "pages#defaultsite" # 1and1 redirection (301)

  # API
  namespace :api, format: :json do
    namespace :v1 do
      resources :users do
        collection do
          get :search
          get :me
          get :facebookconnect
          # follow
          get :is_following
          post :follow
          post :unfollow
          # cart
          get :cart_projects
          get :cart_add
          get :cart_remove
          get :cart_clear
          get :cart_total
          # likes
          get :like_an_update
          get :unlike_an_update
          # other
          get :update_causes
          get :get_places
          get :update_places
          get :update_intelligent_matching
        end
      end
      resources :causes do
        collection do
          get :search
        end
      end
      resources :lifestyle_checkouts
      resources :charities do
        collection do
          get :search
        end
      end
      resources :charity_join_requests do
        collection do
          post :approve
          post :reject
          get :pending
        end
      end
      resources :projects do
        collection do
          get :search
          get :suggested
          get :selected
        end
      end
      resources :faqs
      resources :comments
    end
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::ApplicationController
  skip_authorize_resource :only => [:search, :suggested, :selected]

  def search
    text = params[:query]

    offset = params[:offset] || 0
    limit = params[:limit] || 10

    a = []
    text.split().each do |word|
      Project.public.where("LOWER(projects.name) LIKE ?", "%#{word.downcase}%").each do |project|
        (a.include?(project)) ? a.insert(0, a.delete(project)) : a << project
      end
    end
    @projects = a[offset, limit]

    render :index
  end

  def suggested
    @project = if !params[:project_id].present? || params[:project_id] == '0'
                 if user_signed_in?
                   current_user.suggested_project
                 else
                   Project.public.unfunded.offset(rand(Project.public.unfunded.count))[0]
                 end
               else
                 Project.public.unfunded.find(params[:project_id])
               end
    if @project
      render :suggested
    else
      render json: 'ok'
    end
  end

  def selected
    @projects = []
    @cart.shopping_cart_items.each { |item| @projects << Project.public.unfunded.find(item.item_id) }
    render :index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: :show
  load_resource :charity, only: [:new, :edit, :update]
  load_resource :project, through: :charity, only: [:new, :edit, :update]
  load_resource :project, only: [:show, :destroy]
  authorize_resource except: [:trends, :index]

  respond_to :json, only: [:create, :update]

  def show
    @charity = @project.charity
    @is_subscribed = SubscriptionProject.joins(:subscription).where('subscriptions.user_id' => current_user.id, project_id: @project.id).exists?
  end

  def new
    @project.welcome_messages.build
    @causes = Cause.all
    @makes = Make.all
    @changes = Change.all
  end

  def create
    @charity = Charity.find(params[:charity_id])
    sub_causes_params = params[:project].delete(:cause_sub_causes)
    faqs_params = params[:project].delete(:faqs_attributes)
    @project = Project.new(params[:project].merge({charity_id: @charity.id}))
    @project.add_leader current_user

    ActiveRecord::Base.transaction do
      begin
        manage_sub_causes(sub_causes_params)
        @project.colleague_ids = params[:project][:colleague_ids].split(',') if params[:project][:colleague_ids].present?
        authorize! :update, @project.charity
        @project.save!
        manage_faqs(faqs_params)
        render json: Rabl.render(@project, 'api/v1/projects/show.json', :view_path => 'app/views')
      rescue => e
        render json: project_errors, status: :unprocessable_entity
      end
    end
  end

  def edit
    @causes = Cause.all
    @makes = Make.all
    @changes = Change.all
    @project.welcome_messages.build if @project.welcome_messages.empty?
  end

  def update
    ActiveRecord::Base.transaction do
      begin
        manage_sub_causes
        manage_faqs(params[:project].delete(:faqs_attributes))
        @project.colleague_ids = params[:project][:colleague_ids].split(',') if params[:project][:colleague_ids].present?
        @project.save!
        was_draft = @project.draft
        @project.update_attributes!(params[:project])
        now_is_pending = !@project.draft
        if was_draft && now_is_pending
          ProjectMailer.submit_project_to_requester(@project).deliver
          ProjectMailer.submit_project_to_charity_master_admin(@project).deliver
        end
        render json: Rabl.render(@project, 'api/v1/projects/show.json', :view_path => 'app/views')
      rescue => e
        render json: project_errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to charities_dashboard_path }
    end
  end

  def trends
    @project = Project.find(params[:id])
    authorize! :trends, @project
  end

  private
  def manage_sub_causes(sub_causes_params=nil)
    sub_causes_to_build = []
    sub_causes_to_append = []
    sub_causes_params ||= params[:project].delete(:cause_sub_causes) || {}
    cause_ids = params[:project][:cause_ids] || []

    sub_causes_params.each do |cause_id, sub_cause_list|
      cause_is_selected = cause_ids.include? cause_id
      if cause_is_selected
        sub_causes_split = sub_cause_list[:sub_cause_list].split(",").map(&:strip)
        sub_causes_split.each do |sub_cause_name|
          sub_cause_attributes = { name: sub_cause_name, cause_id: cause_id }
          existing_sub_cause = SubCause.where(sub_cause_attributes).first
          if existing_sub_cause.present?
            sub_causes_to_append.push(existing_sub_cause)
          else
            sub_causes_to_build.push(sub_cause_attributes)
          end
        end
      end
    end

    @project.sub_causes = sub_causes_to_append unless sub_causes_to_append.empty?
    @project.sub_causes.build sub_causes_to_build
  end

  def manage_faqs(faq_params)
    faq_params ||= {}

    faq_params.values.each do |faq_attributes|
      question = faq_attributes[:question]
      if faq_attributes[:_destroy] == '1'
        Faq.destroy faq_attributes[:id]
      elsif question.present?
        answer = faq_attributes[:answer]
        faq = Faq.find_or_create_by_id_and_project_id(faq_attributes[:id], @project.id)
        faq.comments = [Comment.new(text: question, user_id: current_user.id)]
        faq.question.comments = [Comment.new(text: answer, user_id: current_user.id)] if answer.present?
      end
    end
  end

  def project_errors
    errors = @project.errors.messages.keys.zip @project.errors.full_messages
    messages = {
        help: errors.inject([]) { |result, element| result << element.last if @project.help_inputs.include?(element.first); result },
        make: errors.inject([]) { |result, element| result << element.last if @project.make_inputs.include?(element.first); result },
        change: errors.inject([]) { |result, element| result << element.last if @project.change_inputs.include?(element.first); result },
        moreinfo: errors.inject([]) { |result, element| result << element.last if @project.more_info_inputs.include?(element.first); result },
        project: errors.inject([]) { |result, element| result << element.last; result }
    }

    { errors: messages.select {|k,v| v.present?} }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def present_project_field(project, field)
    if field.instance_of? Paperclip::Attachment
      tag :img, src: field.url, width: "100px", height: "100px" if field.file?
    elsif field.instance_of? PastExperiencePhoto
      present_project_field(project, field.photo)
    elsif field.instance_of? WelcomeMessage
      content_tag(:div, field.headline) + present_project_field(project, field.image) + content_tag(:div, field.text)
    elsif field.instance_of? Faq
      content_tag(:div, content_tag(:b, "Q: ") + field.question) + content_tag(:div, content_tag(:b, "A: ") + field.answer)
    elsif field.instance_of? Array
      field.map { |f| present_project_field(project, f) }.join "<br>"
    else
      field.to_s
    end
  end
end

app/views/projects/_causes_sub_causes.html.haml
%div{ class: "control-group #{project.errors.messages[:causes].present? ? 'error' : ''}" }
  = f.label :causes
  - causes.each do |cause|
    - id = "project_cause_ids_#{cause.id}"
    - is_checked = project.cause_ids.include? cause.id
    .checkbox
      %input{id: id, name: "project[cause_ids][]", type: "checkbox", value: cause.id, checked: is_checked}
      %label{for: id}= cause.name

      .control-group
        = f.label :sub_causes
        %input{id: "project_cause_sub_causes_#{cause.id}_sub_cause_list", class: "sub-causes-input", name: "project[cause_sub_causes][#{cause.id}][sub_cause_list]", type: "hidden", data: {subCauses: cause.sub_cause_list}, value: project.sub_cause_list(cause.id)}
  - if project.errors.messages[:causes].present?
    = f.error :causes, class: 'help-inline'

app/views/projects/_change_form.html.haml
.container
  = simple_form_for([charity, project]) do |f|
    .form-errors.change-form
    .form-inputs
      = f.input :change_statement, as: :text, input_html: { rows: 5 }

      #changes
        %h5= t('forms.labels.projects.change_outputs')
        %ul
        = f.simple_fields_for :projects_changes do |change_form|
          %li
            = render 'projects_change_fields', f: change_form
          %hr
        .links
          = link_to_add_association t('forms.actions.projects_changes.add_item'), f, :projects_changes, class: 'btn'
        %hr

      = f.label :change_tags, t('forms.labels.projects.change_tags')
      = f.input :change_tag_list, as: :hidden

      = f.input :past_experience, as: :text, input_html: { rows: 10 }, label: t('forms.labels.projects.past_experience')
      - src = (!project.past_experience_photos.empty? && project.past_experience_photos.first.photo.url) || ""
      - title = (!project.past_experience_photos.empty? && project.past_experience_photos.first.photo_file_name) || ""
      = f.input :past_experience_photos, as: :file, input_html: { class: 'image-with-preview', data: {src: src, title: title }, multiple: 'multiple' }

    .form-actions
      = link_to '#', class: 'btn btn-small btn-inverse prev-section make' do
        .sprites-arrow-to-left.pull-left
        = t('helpers.back')
      = f.button :submit, t('helpers.submit.submit', model: 'Project'), class: 'btn btn-small btn-inverse save-project'
      = link_to '#', class: 'btn btn-small btn-inverse next-section more-info' do
        .sprites-arrow-to-right.pull-right
        = t('helpers.next')

app/views/projects/_change_update.html.haml
#content
  - if @user.achievements_of_followings.any?
    - @user.achievements_of_followings.each do |achievement|
      .box{:class => "boxportfolio#{columns}"}
        .boxcontainer.bloc
          - if achievement.media?
            .image
              = image_tag achievement.media(:cover), width: '400px'

          .content{:class => "#{"with-picture" if achievement.media?} #{"without-change" unless achievement.change && achievement.number}"}
            - if achievement.change && achievement.number
              .medal
                = image_tag achievement.change.icon(:small), width: '79px'
                .count= achievement.number

            = link_to achievement.user do
              = image_tag achievement.user.avatar(:square), width: '60px'
            = link_to achievement.project do
              %h5= achievement.title
            %p= truncate(achievement.text, length: 255) 

          - if user_signed_in?
            %hr

            %ul.actions
              %li
                = link_to "#", :class => 'like-an-update', :'data-likable-id' => achievement.id,
                  :'data-likable-type' => "Achievement", 'data-active' => current_user.liked?(achievement) do
                  .sprites-fav-small
                  %span.text= current_user.liked?(achievement) ? 'Unfav' : 'Fav'
                  %span.number{ data: { count: achievement.likes.size } } (#{achievement.likes.size})
              %li
                = link_to "#", :class => 'comment-an-update',
                  :'data-commentable-id' => achievement.id, :'data-commentable-type' => "Achievement" do
                  .sprites-comment-small
                  Comment
                  %span.number{ data: { count: achievement.comments.count } } (#{achievement.comments.count})
              %li
                -# = link_to "#" do
                %span
                  .sprites-pound-small
                  Top up
                  - if false
                    %span.number (12)

            .comments
              %hr
              .comments-list
                - achievement.comments.each do |comment|
                  .comment
                    %span.user= link_to comment.user.name, comment.user
                    = comment.text
              .submit
                %textarea{name: "comment", placeholder: "Write a comment...", maxlength: "250"}
                = link_to "#", class: "btn btn-inverse", :'data-commentable-id' => achievement.id, :'data-commentable-type' => "Achievement" do
                  .sprites-arrow-to-right.pull-right
                  Add comment

  - else
    No update yet.

app/views/projects/_faq_fields.html.haml
.nested-fields
  = f.input :question, input_html: { value: f.object.question.try(:text) || ''}
  = f.input :answer, as: :text, input_html: { rows: 5, value: f.object.answer.try(:text) || ''}
  = link_to_remove_association t('forms.actions.faqs.remove_item'), f

app/views/projects/_faq_list.html.haml
%ul.unstyled
  - faqs.each do |faq|
    - if faq.answer || (user_signed_in? && faq.question && faq.question.user == current_user)
      %li.faq-item{data: { faq_id: faq.id }}
        %a{"data-target" => "#question-#{faq.question.id}", "data-toggle" => "collapse", type: "button", href: ""}
          = faq.question.text
          - unless faq.answer
            %span.infos (Click here to answer)
          - if can? :destroy, faq
            %span.delete (delete)
        - if faq.answer
          .answer.collapse{id: "question-#{faq.question.id}"}= faq.answer.text
        - else
          .answer.collapse{id: "question-#{faq.question.id}"}
            %textarea{cols: "40", class: "answer_content", name: "answer[content]", rows: "5", maxlength: "254"}
            = link_to nil, class: 'submit btn btn-inverse', data: { question_id: faq.question.id } do
              .sprites-arrow-to-right.pull-right
              Answer

app/views/projects/_help_form.html.haml
.container
  = link_to charities_dashboard_path, class: "btn btn-small btn-inverse" do
    .sprites-arrow-to-right.pull-right
    = t('helpers.skip_project_creation')

  = simple_form_for([charity, project]) do |f|
    .form-errors.help-form
    .form-inputs
      = f.input :help_statement, autofocus: true
      = f.input :help_description, as: :text, input_html: { rows: 5 }
      = f.input :beneficiaries

      = f.input :problem_list
      = f.input :problem_statistic_list

      - src = (project.help_image? && project.help_image.url) || ""
      - title = project.help_image_file_name || ""
      = f.input :help_image, input_html: { class: 'image-with-preview', data: {src: src, title: title } }

      = f.label :tags
      = f.input :tag_list, as: :hidden

      = render 'causes_sub_causes', f: f, project: project, causes: causes

    .form-actions
      = f.button :submit, t('helpers.submit.submit', model: 'Project'), class: 'btn btn-small btn-inverse save-project'
      = link_to '#', class: 'btn btn-small btn-inverse next-section make' do
        .sprites-arrow-to-right.pull-right
        = t('helpers.next')

app/views/projects/_help_make_change.html.haml
- is_invitation ||= false

.row.bloc#help-make-change
  .span4.help
    .image
      = image_tag @project.help_image(:small), width: '345px'
      %h2 Help
      - if is_invitation
        .avatar
          = image_tag 'invitation_avatar.jpg'
    %p= @project.problem

  .span4.make
    .image
      = image_tag @project.make_image(:small), width: '345px'
      %h2 Make
      - if @project.current_project_make
        .avatar
          = image_tag @project.current_project_make.make.icon(:small), width: '79px'
      - elsif @project.previous_project_make
        .avatar
          = image_tag @project.previous_project_make.make.icon(:small), width: '79px'
    %p= @project.solution

  .span4.change
    %h2 Change
    .list
      - @project.projects_changes[0, 2].reverse.each do |project_change|
        - change = project_change.change
        .impact
          = image_tag change.icon(:small), width: '130px'
          .name= truncate change.name, length: 16
    .project-progress-stripes
      - (@project.change_progress / 10).times do |index|
        %div{:class => "sprites-progress-stripe-#{index}"}
      - (10 - @project.change_progress / 10).times do |index|
        %div{:class => "sprites-progress-stripe-empty"}

  - if is_invitation
    .be-a-friend-helping.clearfix
      %h2 Be 1 of X friends helping Matt make change
      .pull-right
        .action
          %a.call-to-action.btn.btn-large.btn-inverse.btn-empty{:href => "#"}
            .sprites-arrow-to-right-black.pull-right
            More about this project
        .action
          %a.call-to-action.btn.btn-large.btn-inverse{:href => "#"}
            .sprites-arrow-to-right.pull-right
            Help Rowena
      .pictures
        - 10.times do
          = link_to "#" do
            = image_tag "friends_helping.jpg"
  - elsif !@project.is_funded
    .pull-right
      = link_to checkout_path(@project.id), class: "call-to-action btn btn-large btn-inverse" do
        .sprites-arrow-to-right.pull-right
        Help make change
      - if @is_subscribed
        .cancel-subscription
          = link_to cancel_stripe_subscription_path(@project.id) do
            (click here to cancel the current subscription)

app/views/projects/_make_form.html.haml
.container
  = simple_form_for([charity, project]) do |f|
    .form-errors.make-form
    .form-inputs
      = f.input :make_statement, as: :text, input_html: { rows: 5 }

      = f.input :activities, as: :text, input_html: { rows: 10 }, label: t('forms.labels.projects.activities')

      #makes
        %h5= t('forms.labels.projects.budget_items')
        %ul
        = f.simple_fields_for :projects_makes do |make_form|
          %li
            = render 'projects/projects_make_fields', f: make_form
          %hr
        .links
          = link_to_add_association t('forms.actions.projects_makes.add_item'), f, :projects_makes, class: 'btn'
        %p#total-price
          = t('forms.labels.projects.total_price')
          %span.price= t('forms.labels.projects.price')
        %hr

      - src = (project.make_image? && project.make_image.url) || ""
      - title = project.make_image_file_name || ""
      = f.input :make_image, input_html: { class: 'image-with-preview', data: {src: src, title: title } }

      = f.label :methods, t('forms.labels.projects.methods')
      = f.input :method_list, as: :hidden

      = f.input :budget_confirmation, label: t('forms.labels.projects.budget_confirmation')

    .form-actions
      = link_to '#', class: 'btn btn-small btn-inverse prev-section help' do
        .sprites-arrow-to-left.pull-left
        = t('helpers.back')
      = f.button :submit, t('helpers.submit.submit', model: 'Project'), class: 'btn btn-small btn-inverse save-project'
      = link_to '#', class: 'btn btn-small btn-inverse next-section change' do
        .sprites-arrow-to-right.pull-right
        = t('helpers.next')

app/views/projects/_more_info_form.html.haml
.container
  = simple_form_for([charity, project]) do |f|
    .form-errors.moreinfo-form
    .form-inputs
      = f.input :headline

      = f.input :location

      %h5= t('forms.labels.projects.welcome_messages')
      #welcome_messages
        = f.simple_fields_for :welcome_messages do |w|
          = render 'projects/welcome_message_fields', f: w

      %h5= t('forms.labels.projects.team_members')
      - if can? :manage_colleagues, project
        = f.label :editors
        = f.association :editors, as: :hidden

        = f.label :reporters
        = f.association :reporters, as: :hidden

        = link_to t('forms.actions.projects.invite_member'), new_user_invitation_path, class: 'hint', target: '_blank'

      %h5= t('forms.labels.projects.faqs')
      #faqs
        = f.simple_fields_for :faqs do |faq|
          = render 'projects/faq_fields', f: faq
        .links
          = link_to_add_association t('forms.actions.faqs.add_item'), f, :faqs

    .form-actions
      = link_to '#', class: 'btn btn-small btn-inverse prev-section change' do
        .sprites-arrow-to-left.pull-left
        = t('helpers.back')
      = f.button :submit, t('helpers.submit.submit', model: 'Project'), class: 'btn btn-small btn-inverse save-project'
      = link_to '#', class: 'btn btn-small btn-inverse next-section submit-project' do
        .sprites-arrow-to-right.pull-right
        = t('helpers.next')

app/views/projects/show.html.haml
.container#project
  .header-container
    %h1= @project.name
    %p
      by
      = link_to @project.charity.name, @project.charity

  = render 'help_make_change'

  .row
    .span8#help-make-column
      - if params[:action] == "project_stage_fundraising"
        = render "project_change_media_booth"
      - elsif params[:action] == "project_stage_development_impact_completion"
        = render "project_change_update", columns: 2

      .faq
        %h2 FAQ's

        .faq-list
          = render 'faq_list', faqs: @project.faqs

        - if user_signed_in? && can?(:create, Faq)
          = label_tag :question_content, "Can’t find what your looking for? Ask your own question below:"
          = text_area :question, :content, rows: 10, maxlength: 254

          = link_to nil, class: 'submit btn btn-large btn-inverse', data: { project_id: @project.id } do
            .sprites-arrow-to-right.pull-right
            Ask

    .span4#change-column
      - if @project.makers.any?
        .total-makers
          - if false
            .pull-right.actions
              = link_to "See all" ,"#"
          %h2
            The Makers
          .bloc.images-only
            - @project.makers[0,6].each do |maker|
              = link_to maker do
                = image_tag maker.avatar(:square), width: '79px'

      .charity-informations
        %h2 Charity informations
        .bloc
          .header
            - if @charity.logo.exists?
              = image_tag @charity.logo(:square), width: '140px'
            - if @charity.leader
              = image_tag @charity.leader.avatar(:square), width: '140px'

          %ul.unstyled
            - if @charity.leader
              %li
                Project leader:
                = @charity.leader.name
            %li
              Projects completed:
              = @charity.projects.funded.count
            %li
              Location:
              = @charity.address
            %li
              Registered charity number:
              = @charity.number

          - if false
            .established-fund-supporters
              %h4 Established fund supporters
              - 4.times do
                = link_to nil do
                  %img{:alt => "", :src => "http://lorempixel.com/70/70/people"}

      .related-projects
        - if false
          .pull-right.actions
            = link_to "See all" ,"#"
        %h2
          Related projects
        .bloc.images-only
          - @project.related_projects[0, 6].each do |project|
            = link_to project do
              = image_tag project.help_image(:square), width: '79px'

      .change.bloc
        .score
          %h5 Project change
          - @project.change_score.to_s.chars.map(&:to_i).each do |digit|
            %div{class: "sprites-digit-#{digit}"}
        .list
          - @project.projects_changes[0, 2].reverse.each do |project_change|
            - change = project_change.change
            .impact
              = image_tag change.icon(:small), width: '130px'
              .name= truncate change.name, length: 16
        .project-progress-stripes
          - (@project.change_progress / 10).times do |index|
            %div{:class => "sprites-progress-stripe-#{index}"}
          - (10 - @project.change_progress / 10).times do |index|
            %div{:class => "sprites-progress-stripe-empty"}

        - unless @project.funded?
          = link_to checkout_path(@project.id), class: "call-to-action btn btn-large btn-inverse" do
            .sprites-arrow-to-right.pull-right
            Help make change