config/routes.rb
App::Application.routes.draw do
  root :to => "home#index"
  get '/blog', to: redirect('http://www.makeworldwide.blogspot.co.uk', status: 302)

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
    sessions: 'users/sessions', invitations: 'users/invitations',
    registrations: 'users/registrations' }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount StripeEvent::Engine => '/stripe/webhooks'

  resources :users
  devise_scope :user do
    post 'invitation/mass' => "users/invitations#mass", as: :mass_invitation
    post 'invitation/generate-link' => "users/invitations#generate_link", as: :generate_invitation_link
    post 'invitation/grant-access' => "waiting_lists#grant_access", as: :grant_access_to_waiting_list
  end
  resources :waiting_lists

  resources :causes
  scope 'charities/dashboard' do
    get 'current-status' => "charities#current_status", as: 'charities_dashboard'
    get 'approvals-new-staff' => "charities#approvals_new_staff", as: 'approvals_new_staff'
  end
  resources :charities, except: :index do
    resources :projects, only: [:new, :create, :edit, :update]
    get "colleagues" => "charities#colleagues", as: :colleagues
    get "projects/:id/trends" => "projects#trends", as: :project_trends
  end

  resources :charity_registrations, only: [:new, :create]
  resources :charity_join_requests, only: [:new, :create]
  resources :stories
  resources :welcome_messages, only: [:show, :destroy]
  resources :projects, only: [:show, :destroy] do
    resources :stories
  end

  # GoCardless
  scope "gocardless" do
    scope "pre-auth" do
      get "index" => "gocardless#pre_auth_index"
      post "submit" => "gocardless#pre_auth_submit"
      get "confirm" => "gocardless#pre_auth_confirm"
    end
    scope "subscription" do
      get "index" => "gocardless#subscription_index"
      post "submit" => "gocardless#subscription_submit"
      get "confirm" => "gocardless#subscription_confirm"
    end
    get "merchant_account_authorization/:state" => "gocardless#merchant_account_authorization", as: :gocardless_merchant_account_authorization
    get "merchant_account_authorization_confirmed" => "gocardless#merchant_account_authorization_confirmed", as: :gocardless_merchant_account_authorization_confirmed
  end
  scope "stripe" do
    # Tests
    get "charges/new" => "stripe#charges_new", as: :new_stripe_charge
    post "charges/create" => "stripe#charges_create", as: :create_stripe_charge
    get "charges/customer" => "stripe#charges_customer", as: :customer_stripe_charge
    get "subscription" => "stripe#subscription", as: :create_stripe_subscription
    # Production
    post "create_charges(/:gift_aid_charity_ids)" => "stripe#create_charges", as: :create_stripe_charges
    post "create_subscriptions(/:gift_aid_charity_ids)" => "stripe#create_subscriptions", as: :create_stripe_subscriptions
    get "merchant_account_authorization/:state" => "stripe#merchant_account_authorization", as: :stripe_merchant_account_authorization
    get "merchant_account_authorization_confirmed" => "stripe#merchant_account_authorization_confirmed", as: :stripe_merchant_account_authorization_confirmed
    get "cancel_subscriptions/:project_id" => "stripe#cancel_subscription", as: :cancel_stripe_subscription
  end

  # _______________ Static pages
  get 'terms-and-conditions' => "pages#terms_and_conditions", as: :terms_and_conditions
  get 'privacy-and-cookies' => "pages#privacy_and_cookies", as: :privacy_and_cookies

  get 'get-started' => "users#waiting_list", as: :waiting_list
  get 'guest/sign-up' => "users#skip_invitation_and_sign_up", as: :skip_invitation_and_sign_up
  post 'guest/create-skipped-invitation' => "users#create_skipped_invitation", as: :create_skipped_invitation

  get "charity-sign-up" => "pages#charity_sign_up", as: :charity_sign_up
  get "personal-sign-up" => "pages#personal_sign_up", as: :personal_sign_up

  get 'change-store-projects' => "pages#change_store_projects", as: 'change_store_projects'
  get 'change-store-projects-category' => "pages#change_store_projects_category"

  get 'project-stage-fundraising' => "pages#project_stage_fundraising"
  get 'project-stage-development-impact-completion' => "pages#project_stage_development_impact_completion"

  get 'checkout/(:project_id)' => "pages#checkout", as: 'checkout'
  get 'payment' => "pages#payment", as: 'payment'

  get 'me' => "pages#me"

  get 'charity-or-bundle-home' => "pages#charity_or_bundle_home", as: 'charity_or_bundle_home'
  get 'charity-or-bundle-updates' => "pages#charity_or_bundle_updates"

  get 'dashboard' => "pages#dashboard"

  get 'received-invitation' => "pages#received_invitation"

  get 'my-home' => "pages#my_home", as: 'my_home'

  get 'causes-preferences-causes' => "pages#causes_preferences_causes", as: 'causes_preferences_causes'
  get 'causes-preferences-places' => "pages#causes_preferences_places"
  get 'causes-preferences-interests' => "pages#causes_preferences_interests", as: 'causes_preferences_interests'
  get 'causes-preferences-collect' => "pages#collect", as: 'causes_preferences_collect'

  get 'defaultsite' => "pages#defaultsite" # 1and1 redirection (301)

  # API
  namespace :api, format: :json do
    namespace :v1 do
      resources :users do
        collection do
          get :search
          get :me
          get :facebookconnect
          # follow
          get :is_following
          post :follow
          post :unfollow
          # cart
          get :cart_projects
          get :cart_add
          get :cart_remove
          get :cart_clear
          get :cart_total
          # likes
          get :like_an_update
          get :unlike_an_update
          # other
          get :update_causes
          get :get_places
          get :update_places
          get :update_intelligent_matching
        end
      end
      resources :causes do
        collection do
          get :search
        end
      end
      resources :lifestyle_checkouts
      resources :charities do
        collection do
          get :search
        end
      end
      resources :charity_join_requests do
        collection do
          post :approve
          post :reject
          get :pending
        end
      end
      resources :projects do
        collection do
          get :search
          get :suggested
          get :selected
        end
      end
      resources :faqs
      resources :comments
    end
  end
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  acts_as_followable

  scope :public, -> { where(is_public: true) }
  scope :pending, -> { where("is_public = ? OR chv1_file_name IS NULL OR contract_file_name IS NULL OR paying_in_slip_file_name IS NULL OR hmrc_number IS NULL OR charity_regulator IS NULL", false) }

  belongs_to :leader, class_name: 'User', foreign_key: 'leader_id'
  has_many :projects
  has_and_belongs_to_many :reporters, :class_name=> "User", join_table: :charities_reporters, :after_add => :after_add_colleague
  has_and_belongs_to_many :editors, :class_name=> "User", join_table: :charities_editors, :after_add => :after_add_colleague

  has_one :go_cardless_merchant
  has_one :stripe_merchant

  has_many :stripe_customers
  has_many :subscriptions
  has_many :donations

  attr_accessible :logo
  has_attached_file :logo,
                    :styles => { square: "200x200#", small: "400x400>", profile: "240x175#" },
                    :path => "charities/:id/logo/:style/:filename",
                    :default_url => "/assets/charities/logo/:style/logo.png"
  validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/jpg', 'image/png']

  attr_accessible :chv1
  has_attached_file :chv1, :path => "charities/:id/chv1/:filename"
  validates_attachment_content_type :chv1, :content_type => /\Aimage\/.*\Z|\Aapplication\/pdf\Z/

  attr_accessible :contract
  has_attached_file :contract, :path => "charities/:id/contract/:filename"
  validates_attachment_content_type :contract, :content_type => /\Aimage\/.*\Z|\Aapplication\/pdf\Z/

  attr_accessible :paying_in_slip
  has_attached_file :paying_in_slip, :path => "charities/:id/paying_in_slip/:filename"
  validates_attachment_content_type :paying_in_slip, :content_type => /\Aimage\/.*\Z|\Aapplication\/pdf\Z/

  attr_accessible :leader_id, :address, :description, :name, :number, :is_public, :hmrc_number, :charity_regulator, :landline_phone, :mobile_phone, :skype, :email, :office_address, :registered_charity_address, :notes
  attr_accessible :project_ids, :admin_ids, :reporter_ids, :editor_ids

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :number, presence: true
  if [:staging, :production].include? Rails.env # paperclip - http://stackoverflow.com/questions/17333072/railspaperclipimagemagickwindows-7-got-error-500
    validates :logo, presence: true
  end
  validate :cant_be_public_if_not_ready_for_approval

  def stories
    list = []
    projects.each do |project|
      project.stories.each { |story| list << story }
    end
    list
  end

  def change_score
    projects.sum(&:change_score).to_i
  end

  def change_progress
    total = projects.sum(&:change_progress)
    progress = total / projects.count if projects.any?
    progress = 100 if progress > 100
    progress
  end

  def projects_leaders
    list = []
    projects.each { |project| list << project.leader if project.leader }
    list.uniq
  end

  def makes
    list = []
    projects.each do |project|
      project.projects_makes.active.each do |project_make|
        list << project_make.make if project_make.make
      end
    end
    list
  end

  def causes
    causes = []
    projects.each do |project|
      project.causes.each { |cause| causes << cause }
    end
    causes.uniq
  end

  def colleagues
    (reporters + editors).uniq
  end

  def donors
    []
  end

  def current_donors
    []
  end

  def donors_wanted_to_give_again
    []
  end

  def path
    Rails.application.routes.url_helpers.charity_path(self)
  end

  def self.get_merchant_customer(charity, user)
    if charity.stripe_merchant
      merchant_access_token = charity.stripe_merchant.access_token
      stripe_customer = StripeCustomer.find_or_create_by_charity_id_and_user_id(charity.id, user.id)

      if stripe_customer.customer_id
        merchant_customer = Stripe::Customer.retrieve(stripe_customer.customer_id, merchant_access_token)
      else
        # Find and save shared customer
        if customer = user.stripe_customer
          token = Stripe::Token.create({
            customer: customer.customer_id
          }, merchant_access_token)

          merchant_customer = Stripe::Customer.create({
            email: user.email,
            card: token.id
          }, merchant_access_token)

          stripe_customer.customer_id = merchant_customer.id
          stripe_customer.save
        end
      end

      merchant_customer
    else
      charity.is_public = false
      charity.save
      false
    end
  end

  def leader
    read_attribute(:leader) || self.editors.first
  end

  def add_leader(user)
    self.editors << user
    self.leader = user
  end

  def add_member(user)
    self.editors << user
  end

  extend FriendlyId
  friendly_id :name, use: :slugged

  def charity_regulator_enum
    CharityRegulators.all
  end

  def my_charity_regulator
    [ CharityRegulators.selected_regulator(charity_regulator), charity_regulator ]
  end

  rails_admin do
    edit do
      exclude_fields :slug, :followings, :go_cardless_merchant, :stripe_merchant, :stripe_customers, :subscriptions, :donations
      configure :charity_regulator, :enum do
        def form_value
          bindings[:object].my_charity_regulator
        end

        multiple do
          false
        end

        def render
          bindings[:view].render :partial => "form_enumeration_with_other", :locals => {:field => self, :form => bindings[:form]}
        end
      end
    end
  end

  private
    def after_add_colleague(user)
      if Rails.env.production?
        NotificationsMailer.delay.added_new_colleague_to_a_charity(user, self)
      else
        NotificationsMailer.added_new_colleague_to_a_charity(user, self).deliver unless Rails.env.development?
      end
    end

    def cant_be_public_if_not_ready_for_approval
      if is_public && !(chv1? && contract? && paying_in_slip? && hmrc_number.present? && charity_regulator.present?)
        errors.add(:base, I18n.t('activerecord.errors.messages.models.charity.attributes.is_public'))
      end
    end
end

app/controllers/api/v1/charities_controller.rb
class Api::V1::CharitiesController < Api::ApplicationController
  skip_authorize_resource :only => :search
  
  def search
    text = params[:query]

    offset = params[:offset] || 0
    limit = params[:limit] || 10

    a = []
    text.split().each do |word|
      Charity.public.where("LOWER(name) LIKE ?", "%#{word.downcase}%").each do |charity|
        (a.include?(charity)) ? a.insert(0, a.delete(charity)) : a << charity
      end
    end
    @charities = a[offset, limit]

    render :index
  end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_filter :authenticate_user!, except: :show
  before_filter :current_status_logic, only: [:current_status, :approvals_new_staff]
  load_and_authorize_resource except: [:current_status, :approvals_new_staff, :colleagues]

  def show
    @is_following = user_signed_in? ? @charity.followed_by?(current_user) : false
  end

  def new
    @charity.number ||= flash[:charity_number] if flash[:charity_number]
  end

  def create
    @charity.add_leader current_user
    respond_to do |format|
      if @charity.save
        format.html { redirect_to new_charity_project_path(@charity), notice: I18n.t('layouts.flash_messages.charity_created') }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @charity.update_attributes(params[:charity])
        @charity.editor_ids = params[:charity][:editor_ids].split(',') if params[:charity][:editor_ids].present?
        @charity.reporter_ids = params[:charity][:reporter_ids].split(',') if params[:charity][:reporter_ids].present?
        @charity.save
        format.html { redirect_to charities_dashboard_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  def colleagues
    @charity = current_user.charities.first
    authorize! :update, @charity if @charity
  end

  private

  def current_status_logic
    number_of_projects_and_charities_to_manage = current_user.charities_as_editor.count +
                                                 current_user.charities_as_reporter.count +
                                                 current_user.projects_as_editor.count +
                                                 current_user.projects_as_reporter.count

    if number_of_projects_and_charities_to_manage == 1
      if current_user.charities_as_editor.count == 1 || current_user.charities_as_reporter.count == 1
        @charity = current_user.charities.first
        @project = current_user.projects_as_colleague.first unless @charity
      end
    end

    if params[:charity_id]
      @charity = Charity.find(params[:charity_id])
    elsif params[:project_id]
      @project = Project.find(params[:project_id])
    end

    @display_menu = number_of_projects_and_charities_to_manage > 1 && @charity.nil? && @project.nil?

    if @charity
      authorize! :dashboard, @charity

      # staff at related projects
      @staff = []
      @charity.causes.each do |cause|
        if project = cause.projects.offset(rand(Project.count)).first
          @staff << project.leader if project.leader && project.charity != @charity && project.leader != current_user
          @staff.uniq!
        end
      end
      if @staff.count < 10
        (10 - @staff.count).times do
          if project = Project.offset(rand(Project.count)).first
            @staff << project.leader if project.leader && project.charity != @charity && project.leader != current_user
          end
        end
      end
      @staff.uniq!
      # .staff at related projects
    end

    if @project
      authorize! :dashboard, @project
    end
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_approvals_new_staff.html.haml
.container
  %h1 NEW STAFF

  #pending-join-requests

app/views/charities/_current_status.html.haml
- if @display_menu
  .container
    %h1 Charity/project dashboard
    %hr

    %h1 Choose the charity or project you would like to see

    %h3 Charities I am an editor
    %ul
      - current_user.charities_as_editor.each do |charity|
        %li= link_to charity.name, charities_dashboard_path(charity_id: charity.id)

    %h3 Charities I am a reporter
    %ul
      - current_user.charities_as_reporter.each do |charity|
        %li= link_to charity.name, charities_dashboard_path(charity_id: charity.id)

    %h3 Projects I am an editor
    %ul
      - current_user.projects_as_editor.each do |project|
        %li
          = link_to charities_dashboard_path(project_id: project.id) do
            = "#{project.name} (#{project.present_status})"

    %h3 Projects I am a reporter
    %ul
      - current_user.projects_as_reporter.each do |project|
        %li
          = link_to charities_dashboard_path(project_id: project.id) do
            = "#{project.name} (#{project.present_status})"

- else
  .container
    - if @charity
      %h1 Charity dashboard
      %hr
      %h1= link_to @charity.name, @charity
      %dl.dl-horizontal
        %dt Description
        %dd= @charity.description
        %dt Address
        %dd= @charity.address
        %dt Number
        %dd= @charity.number
        %dt Leader
        %dd= @charity.leader.try(:name)

      - if can? :update, @charity
        %hr

        %h4 Payments
        - if @charity.is_public
          = link_to "View public page", @charity, class: 'btn'
        - else
          %p
            You need to connect with GoCardless and Stripe in order to accept payments.
            Your charity will not be visible in the website until it's done.
        %ul
          %li
            - if @charity.go_cardless_merchant && @charity.go_cardless_merchant.access_token
              Your GoCardless account (direct debit) is well configured.
            - else
              = link_to "Connect with GoCardless (direct debit)", gocardless_merchant_account_authorization_url(@charity.id), class: 'btn'
          %li
            - if @charity.stripe_merchant && @charity.stripe_merchant.access_token
              Your Stripe account (credit card) is well configured.
            - else
              = link_to "Connect with Stripe (credit card)", stripe_merchant_account_authorization_url(@charity.id), class: 'btn'

        %hr

      %ul.inline
        - if can? :update, @charity
          %li= link_to "Edit charity", edit_charity_path(@charity), class: 'btn'

      .row
        .span8
          %h2
            Projects
            (#{@charity.projects.count})
          - if @charity.projects.empty?
            No project yet --
            = link_to "click here to add one.", new_charity_project_path(@charity)
          - else
            - @charity.projects.each do |project|
              %hr
              = render 'project_dashboard', project: project

        .span4
          %h3 Charity stats
          %ul.unstyled
            %li
              Number of current donors:
              = @charity.current_donors.count
            %li
              Total number of donors:
              = @charity.donors.count
            %li
              Number donors wanting to give again to a project by that charity:
              = @charity.donors_wanted_to_give_again.count

          %ul.unstyled
            %li= link_to "Create new project", new_charity_project_path(@charity), class: 'btn'
            - if false
              %li= link_to "Download donor statistics CSV file", "#", class: 'btn'

          %hr

          - if @charity.editors.any?
            %h5 Editors
            - @charity.editors.each do |user|
              .colleague
                = link_to image_tag(user.avatar(:square), width: '50px'), user
                = user.name
          - if @charity.reporters.any?
            %h5 Reporters
            - @charity.reporters.each do |user|
              .colleague
                = link_to image_tag(user.avatar(:square), width: '50px'), user
                = user.name
          - if can? :update, @charity
            .actions
              = link_to "Manage editors and reporters", charity_colleagues_path(@charity), class: 'btn'
      .row
        %hr
        %h3 Staff at related charities
        - @staff.each do |user|
          = image_tag  user.avatar(:square), width: '60px'
    - elsif @project
      %h1 Project dashboard
      %hr
      = render 'project_dashboard', project: @project
    - else
      %h1 Charity dashboard
      %hr
      = link_to "Click here to add a charity", new_charity_path, class: "btn"

- if current_user.has_role? :admin
  .container
    %h1 Makerble admin
    %hr

    %h3 Charities
    %ul
      - Charity.all.each do |charity|
        %li= link_to charity.name, charities_dashboard_path(charity_id: charity.id)

app/views/charities/_dashboard.html.haml
#charities-dashboard.charities-dashboard
  .container
    %ul.nav.nav-tabs.dashboard-tabs
      %li{class: "#{"active" if params[:action] == "current_status"}", data: {name: "current-status"} }
        %a(href="#current-status" data-toggle="tab") Current Status Dashboard
      %li.dropdown{ class: "#{"active" if params[:action].start_with?("approvals")}" }
        %a#approvals-drop.dropdown-toggle(href="#" data-toggle="dropdown")
          Approvals
          %b.caret
        %ul.dropdown-menu(role="menu" aria-labelledby="approvals-drop")
          %li{class: "#{"active" if params[:action] == "approvals_new_staff"}", data: {name: "approvals-new-staff"} }
            %a(href="#approvals-new-staff" tabindex="-1" data-toggle="tab") New Staff
          -# %li data-menu="approvals-new-projects"
          -#   %a(href="#approvals-new-projects" tabindex="-1" data-toggle="tab") New Projects

    .wrapper-sprites-line-help-make-change.sprites-line

  .tab-content
    #current-status.tab-pane.fade{:class => "#{"active in" if params[:action] == "current_status"}"}
      = render 'current_status'
    #approvals-new-staff.tab-pane.fade{:class => "#{"active in" if params[:action] == "approvals_new_staff"}"}
      = render 'approvals_new_staff'
    -# #approvals-new-projects.tab-pane.fade
    -#   = render 'approvals_new_projects'

app/views/charities/_form.html.haml
= simple_form_for(@charity) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, autofocus: true
    = f.input :description, input_html: { rows: 5 }
    = f.input :address, input_html: { rows: 2 }
    = f.input :number
    = f.input :logo

  .form-actions
    = f.button :submit

app/views/charities/_home_tab_pane.html.haml
.cover
.container
  .header
    = image_tag @charity.logo(:profile)
    - unless @charity.makes.empty?
      .changes
        - @charity.makes[0,2].each do |make|
          = image_tag(make.icon(:normal), width: "176px")

  .score 
    %hr
    .pull-right.digits
      - @charity.change_score.to_s.chars.map(&:to_i).each do |digit|
        %div{class: "sprites-digit-#{digit}"}
    %h2 MAKERBLE Change Score
    %hr

  .row
    - unless @charity.projects.public.empty?
      .span8
        %h2
          Projects
          - if false
            %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
              .sprites-infos
        .bloc
          .projects
            - @charity.projects.public.reverse[0..5].each do |project|
              .project
                = link_to project do
                  = image_tag project.help_image(:square), width: '219px'
                  .name= project.name

          .clearfix
          -# = render 'shared/pagination'

    - if false
      .span4.latest-updates
        .pull-right.actions
          = link_to "See all" ,"#"
        %h2
          Latest updates
          %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
            .sprites-infos
        .bloc
          = link_to "#" do
            .sprites-arrow-to-left-black-thin
          %ul
            = render partial: 'timeline/medal', locals: { name: 'qualifications', title: 'Qualifications', count: 1, popover_placement: 'right' }
          = link_to "#" do
            .sprites-arrow-to-right-black-thin
          
    - if false
      .span4.total-makers
        .pull-right.actions
          = link_to "See all" ,"#"
        %h2
          Total makers
          %span.count (12)
          %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
            .sprites-infos
        .bloc.images-only
          - 6.times do
            = link_to "#" do
              = image_tag "http://placehold.it/79x71"

    - unless @charity.projects_leaders.empty?
      .span4.project-leaders
        - if false
          .pull-right.actions
            = link_to "See all" ,"#"
        %h2
          Project leaders
          %span.count= "(#{@charity.projects_leaders.count})"
          - if false
            %a.infos{"data-original-title" => "Infos", "data-toggle" => "tooltip", :href => "#", :title => ""}
              .sprites-infos
        .bloc.images-only
          - @charity.projects_leaders.each do |project_leader|
            = link_to project_leader do
              = image_tag project_leader.avatar(:square), width: '79px'

  %hr

  .footer.charity-footer-details
    - if @charity.leader
      = link_to @charity.leader do
        = image_tag @charity.leader.avatar(:square), width: '141px'
    
    = link_to @charity do
      = image_tag @charity.logo(:square), width: '141px'

    %ul.unstyled
      - if @charity.leader
        %li
          Project leader:
          = @charity.leader.name
      %li
        Projects completed:
        = @charity.projects.funded.count
      %li
        Location:
        = @charity.address
      %li
        Registered charity number:
        = @charity.number

    - if false
      .established-fund-supporters
        %h5 Established fund supporters
        - 4.times do  
          = link_to "#" do
            = image_tag "http://placehold.it/70x63"

app/views/charities/_project_dashboard.html.haml
%h2
  = link_to project do
    = "#{project.name} (#{project.present_status})"
%ul.inline
  - if project.approved
    %li= link_to "View public page", project, class: 'btn'
  - if can? :update, project
    %li= link_to "Edit project", edit_charity_project_path(project.charity, project), class: 'btn'
  - if can? :destroy, project
    %li= link_to "Delete project", project, method: :delete,
      confirm: "Are you sure that you want to delete this project?", class: 'btn'
  -# - if can? :update, project
  -#   - special_welcome_message_path = project.welcome_message ? edit_project_welcome_message_path(project, project.welcome_message) : new_project_welcome_message_path(project)
  -#   %li= link_to "View / Edit welcome message", special_welcome_message_path, class: 'btn'

%dl.dl-horizontal
  %dt Help thumbnail
  %dd= image_tag project.help_image(:small), width: "100px"
  %dt Make thumbnail
  %dd= image_tag project.make_image(:small), width: "100px"

  %dt Funding progress
  %dd= project.change_score

  %dt Number of makers
  %dd= project.makers.count

%h2
  Updates
  (#{project.stories.count})

%ul.unstyled
  - project.stories.each do |story|
    %li
      = truncate story.text
      = ": #{story.number} #{story.change.name}"
      = "(not approved yet)" if can?(:update, story) && !story.approved
      - if can? :update, story
        = link_to "Edit", edit_project_story_path(story.project, story)
      - if can? :destroy, story
        = link_to "Delete", project_story_path(story.project, story), method: :delete

%ul.inline
  %li= link_to "Write update", new_project_story_path(project), class: 'btn'
  - if can? :trends, project
    %li= link_to "View project trends", charity_project_trends_path(project.charity, project), class: 'btn'

app/views/charities/_updates_tab_pane.html.haml
.container
  #content
    = render @charity.stories

app/views/charities/approvals_new_staff.html.haml
= render 'dashboard'

app/views/charities/colleagues.html.haml
.container
  %h1 Manage colleagues
  = link_to "Your colleague is not on Makerble yet? Click here to send an invitation.", new_user_invitation_path, class: 'hint', target: '_blank'

  = simple_form_for(@charity) do |f|

    %p
      An editor can; write change updates, edit reporters change updates, approve and pubish change updates,
      write a new project, approve and publish a project, amend an existing project.
    = f.label :editors, "Editors"
    = f.association :editors, as: :hidden
    
    %p
      A reporter can; write change updates and write a new project.
    = f.label :reporters, "Reporters"
    = f.association :reporters, as: :hidden
    
    = f.submit

app/views/charities/current_status.html.haml
= render 'dashboard'

app/views/charities/edit.html.haml
.container
  %h1 Editing charity

  = render 'form'

  = link_to 'Show', @charity
  \|
  = link_to 'Back', charities_path

app/views/charities/index.html.haml
.container
  %h1 Listing charities

  %table
    %tr
      %th Name
      %th Description
      %th Address
      %th Number
      %th
      %th
      %th

    - @charities.each do |charity|
      %tr
        %td= charity.name
        %td= charity.description
        %td= charity.address
        %td= charity.number
        %td= link_to 'Show', charity
        %td= link_to 'Edit', edit_charity_path(charity)
        %td= link_to 'Destroy', charity, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Charity', new_charity_path

app/views/charities/new.html.haml
.container
  %h1 New charity

  = render 'form'